### ISSUE TITLE
max depth

### ISSUE THREAD

**Issue by abdelrahmanmasoud** [visibilitydataset/visibilitydataset.github.io#1]
Thanks alot for this useful dataset.I would just like to know what is the max depth of the campus-night dataset?

**Comment by alexjunholee** [comment]
I guess it can be presumed by the sensor sheet.
Ouster OS1-64 has 120m range.

**Comment by abdelrahmanmasoud** [comment]
Thanks alot

**Comment by alexjunholee** [comment]
:)
