### ISSUE TITLE
Thermal to Lidar calibration file

### ISSUE THREAD

**Issue by SayedNadim** [visibilitydataset/visibilitydataset.github.io#2]
Hi,
Thanks for your great work. 
Can you please provide the thermal to lidar calibration parameters? I couldn't find it in the calibration file.
Thanks again.

**Comment by alexjunholee** [comment]
Thanks for your attention to our dataset.

We already provided the extrinsic transformation of (Thermal-RGB) and (LiDAR-RGB) in both sensor systems. You may obtain the transformation of (Thermal-LiDAR) by multiplying the relative translations in the SE3 matrix (4*4) form.
$T_{LiDAR,ther}$
= $(T_{ther,LiDAR})^{-1}$
= $(T_{ther,RGB}*T_{RGB,LiDAR})^{-1}$
= $T_{LiDAR,RGB} * T^{-1}_{ther,RGB} $

Thanks!
