### ISSUE TITLE
Thermal image pre-processing

### ISSUE THREAD

**Issue by SayedNadim** [visibilitydataset/visibilitydataset.github.io#3]
Hi, thanks again for the great work. 
I am wondering about the thermal image pre-processing. I have a FLIR Boson LWIR camera and I recorded some images with it. When I checked the max and min values of the images, I found them to be around ```23000``` and ```22631```. But when I checked the same with ```outdoor_robust_night1```, I found them to be around ```3200``` and ```1958```. Do you have any hint on this?

This is my code for recording the thermal images.
```
# capture.py
import cv2
#
cap = cv2.VideoCapture(2)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 512)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter.fourcc('Y', '1', '6', ' '))
cap.set(cv2.CAP_PROP_CONVERT_RGB, 0)

framecount = 200
frame_buf = []
for _ in range(framecount):  # record indefinitely (until user presses q), replace with "while True"
    stream_ret, frame = cap.read()
    if stream_ret:
        frame = cv2.flip(frame, -1)
        print(frame.shape)
        cv2.imshow("image", frame)
        if cv2.waitKey(1) == ord('q'):
            break;
        frame_buf.append(frame)
#
cv2.destroyAllWindows()

folder = './Thermal/'

# Below is example code to save images to "folder" (Use appropriate directory syntax.)
num = 0
while len(frame_buf) > 0:
    cv2.imwrite(f'{folder}/cap_{num}.png', frame_buf.pop(0))
    num += 1
```

Here's one of the captured images.
![cap_198](https://user-images.githubusercontent.com/11741497/200975601-bec69e74-bb0d-4840-83ca-54a8e21e45ae.png)

Thanks in advance.

**Comment by alexjunholee** [comment]
Hi,

As the transformation function of each camera is different,
You may convert the values into temperature with our own function.

Please refer to the raw_to_kelvin function in the ``process_img.py``.
```
def raw_to_kelvin(val):
    return ( 1428.0 / log( 408825.0 / ( val + 58.417 ) + 1.0 ) )
```

Thanks!

**Comment by SayedNadim** [comment]
Thank you for answering. I will try and get back to you. Best wishes!

**Comment by SayedNadim** [comment]
Can you please tell me the meanings of the values used in this equation? I would much appreciate it if you could refer me to some links.

**Comment by alexjunholee** [comment]
You may refer to the original FLIR camera driver's [source code](https://github.com/KumarRobotics/flir_gige/blob/77301f24a6862b53018a02c46c3dda166155347a/include/flir_gige/planck.h).

**Comment by SayedNadim** [comment]
Thanks a lot. Closing the issue now.
