### ISSUE TITLE
How to heat the PCB calibtration board

### ISSUE THREAD

**Issue by cpymaple** [visibilitydataset/visibilitydataset.github.io#5]
Hi, thanks for the great work.

In the paper, "We used a calibration board made of aluminum coating on the printed circuit board (PCB),..., the board
was heated before calibration".

But how exactly do you heat the calibration board? Using a hairdryer or other tools?

**Comment by visibilitydataset** [comment]
Hi!

You can simply use a heat gun (or a hair dryer of course).

Best,
Alex

2023년 7월 13일 (목) 오후 6:57, CHEN PEIYU ***@***.***>님이 작성:

**Comment by cpymaple** [comment]
Thanks for your quick reply!

But I still have some questions about how to make the aluminum checkerboard:

1. Does this manually affix the aluminum sheets to the PCB?
2. Or is the checkerboard machined directly into a complete metal-aluminum part?

**Comment by visibilitydataset** [comment]
Hi,

I am not sure what your question is, however, the procedure was done as the
identical procedure of making a standard printed circuit board, which
includes no manual attachment.

Best,
Alex

2023년 7월 14일 (금) 오전 11:57, CHEN PEIYU ***@***.***>님이 작성:

**Comment by cpymaple** [comment]
Thanks for your reply. That can solve my problems. Have a nice day~
