### ISSUE TITLE
OS1-64 IMU Parameters

### ISSUE THREAD

**Issue by jonathansel** [visibilitydataset/visibilitydataset.github.io#6]
Hello, 

Thank you for the great work.

I was wondering if you could share the IMU configuration for the InvenSense ICM-20948 (Built-in OS1-64 IMU) used in driving sequences. Perhaps this was used in the estimation of the extrinsics? 

i.e.
```
#Accelerometers
accelerometer_noise_density: 1.86e-03   #Noise density (continuous-time)
accelerometer_random_walk:   4.33e-04   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     1.87e-04   #Noise density (continuous-time)
gyroscope_random_walk:       2.66e-05   #Bias random walk

rostopic:                    /imu0      #the IMU ROS topic
update_rate:                 200.0      #Hz (for discretization of the values above)
```

**Comment by alexjunholee** [comment]
Hi!

Thanks for paying attention to our dataset.

It's been quite a long after this study, so I am not very sure of the specific parameter. However, you can find the parameters from the [spec sheet](https://product.tdk.com/system/files/dam/doc/product/sensor/mortion-inertial/imu/data_sheet/ds-000189-icm-20948-v1.5.pdf) of the sensor ICM-20948.

Reading from the spec sheet shows as follows:
accelerometer_noise_density: 2.3e-04 (230 ug)
accelerometer_random_walk: 2.5e-02 (25 mg)

gyroscope_noise_density: 1.5e-02 (0.015 dps/√Hz)
gyroscope_random_walk:  5e-00 (5 dps)

The value from the spec sheet seems to have quite a different tendency to the elaborative IMUs, so you can use your own calibration by [IMU instrinsic calibration tools](https://github.com/ori-drs/allan_variance_ros) instead.

Thanks!

**Comment by jonathansel** [comment]
Thank you for the information and helpful resources!
